dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 4 #32
  dataset_path: EyeDatasets:split=TRAIN #ImageNet22k
  centering: sinkhorn_knopp
student:
  arch: vit_base #vit_large
  pretrained_weights: '/home/jovyan/dinov2/pretrained_models/dinov2_vitb14_reg4_pretrain.pth' #pu add
  patch_size: 14
  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 4
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 500
  weight_decay_end: 0.2
  base_lr: 0.01 #2.0e-04  # learning rate for a batch size of 1024
  lr: 0.01 #pu
  warmup_epochs: 80
  layerwise_decay: 1.0
crops:
  local_crops_size: 98